# docker-compose.yml文件的版本
version: "2"
# 管理的服务
services:
  corntab_master:
    # 指定镜像
    image: ccr.ccs.tencentyun.com/corntab/master:v1.0.0
    ports:
    # 端口映射
    - 8070:8070
    ulimits:
      nproc: 65535
      nofile:
       soft: 20000
       hard: 40000
    logging: 
      driver: "json-file"
      options: 
        max-size: "1g"
