# docker-compose.yml文件的版本
version: "2"
# 管理的服务
services:
  redis:
    # 指定镜像
    image: redis:latest
    command: redis-server --requirepass 123456
    ports:
    # 端口映射
    - 6379:6379
    volumes:
    # 目录映射
    - "${REDIS_DIR}/conf:/data/db"
    - "${REDIS_DIR}/data:/data"
  
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxx
    ports:
      - "3306:3306"
    volumes:
    - "${MYSQL_DIR}/data:/data/db"
    - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
    
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - "${MONGODB_DIR}/data:/data/db"
    - "${MONGODB_DIR}/etc/localtime:/etc/localtime"
