# 使用docker:  https://github.com/wurstmeister/kafka-docker.git
# 修改 vim docker-compose-single-broker.yml
# 启动 docker-compose -f docker-compose-single-broker.yml up -d
# 需要在本地启动
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "log:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
